version: '3.9'

services:
  spok_backend:
    build: .
    image: spok_backend
    container_name: spok_backend
    #runtime: nvidia
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - .:/workspace
    networks:
      - spok_network

networks:
  spok_network:
    driver: bridge
